# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

branches:
  only:
    - master

install:
  pip install -r requirements.txt

jobs:
  include:
    - stage: "Tests"
      name: "Travis tests"
      script: pytest
    deploy:
      name: "Deploy to PyPi"
      provider: pypi
      username: ${{ secrets.PYPI_USERNAME }}
      password: ${{ secrets.PYPI_PASSWORD }}
      skip_cleanup: true
      skip_existing: true
      on:
        branch: master
        # tags: true
    # - name: Clean
    #   run: |
    #     rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info