# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

install: pip install -r requirements.txt

script: pytest

stages:
  - test
  - name: deploy
    if: branch = master
  - name: clean
    if: branch = master

test-job:
  stage: test
  script:
    - pytest

deploy-test-job:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -r testpypi dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
deploy-job:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}

clean-job:
  stage: clean
  script:
    rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info