# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

os: linux

dist: xenial

install:
  pip install -r requirements.txt

script: pytest

deploy:
  name: "Deploy to PyPi"
  provider: pypi
  username: ${{ secrets.PYPI_USERNAME }}
  password: ${{ secrets.PYPI_PASSWORD }}
  cleanup: true
  skip_existing: true
  on:
    branch: master
    tags: true

script:
  rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info