# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

# USE LINUX OR WINDOWS PS??
#   HOW TO GET ENV VARIABLES FROM GIT -> SHELL ???
os: windows

jobs:
  include:
    - name: Orient
      script:
        - dir
    
    - name: Requirements
      script:
        - pip install -r requirements.txt
    
    - name: Test
      script:
        - pytest
    
    - name: Build
      script:
        - python setup.py sdist bdist_wheel
    
    - name: Deploy to testpypi
      script:
        - pwsh - $PYPI_TEST_USERNAME = ${{ secrets.PYPI_TEST_USERNAME }}
        - $PYPI_TEST_PASSWORD = ${{ secrets.PYPI_TEST_PASSWORD }}
        - twine upload dist/* -r testpypi -u ${PYPI_TEST_USERNAME} -p ${PYPI_TEST_PASSWORD}
    
    - name: Deploy to pypi
      if: branch = master
      script:
        - $PYPI_USERNAME = ${{ secrets.PYPI_USERNAME }}
        - $PYPI_PASSWORD = ${{ secrets.PYPI_PASSWORD }}
        - twine upload dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
    
    - name: Clean
      script:
        - dir
        - rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
        - dir