# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

install: pip install -r requirements.txt

script: pytest

stages:
  - Orient
  - Test
  - name: Deploy
    if: branch = master
  - name: Clean
    if: branch = master

jobs:
  include:
    - stage: Orient
      script:
        pwd
        tree
    - stage: Unit tests
      script: pytest
    
    - stage: Deploy to PyPi
      script: python setup.py sdist bdist_wheel
      deploy:
        provider: pypi
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        cleanup: true
        skip_existing: true
        on:
          branch: master
          tags: false
        
    - stage: Clean
      script:
        rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info