# Runs tests and deploys to PyPi

language: python

python: "3.8"

os: linux

dist: xenial

jobs:
  include:    
    - name: Test & Deploy
      if: branch = master
      script:
        # Orient
        - dir
        # Install Requirements
        - pip install -r requirements.txt
        # Test"
        - pytest
        # Bundle Distribution
        - python setup.py sdist bdist_wheel
        # Deploy to testpypi
        - twine upload dist/* -r testpypi -u ${PYPI_TEST_USERNAME} -p ${PYPI_TEST_PASSWORD}
        # Deploy to pypi
        - twine upload dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
        # Clean Files
        - dir
        - rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
        - dir
       