# Upon a push to master, runs tests and deploys to PyPi
# INPUT API KEY TO PASSWORD TO DEPLOY
language: python

python:
  "3.8"

install:
  pip install -r requirements.txt

script:
  pytest

deploy:
  provider: pypi
  username: "__token__"
  password: # FILL ME IN TO DEPLOY
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true  # May want to disable to ease deployment
    branch: master