# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master

language: python

python:
  "3.8"

install:
  pip install -r requirements.txt

script:
  pytest

jobs:
  deploy:
    - name: Deploy to PyPi
    provider: pypi
    username: ${{ secrets.PYPI_USERNAME }}
    password: ${{ secrets.PYPI_PASSWORD }}
    skip_cleanup: true
    skip_existing: true
    on:
      tags: false
      branch: master
    - name: Clean
      run: |
        rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info