# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

os: linux

dist: xenial

install: pip install -r requirements.txt

script: pytest

jobs:
  include:
    - name: Orient
      script:
        - dir
    
    - name: Test
      script: pytest
    
    - name: Build
      script:
        - python setup.py sdist bdist_wheel
    
    - name: Deploy TEST
      env:
        PYPI_TEST_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
        PYPI_TEST_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
      script:
        - twine upload dist/* -u "$PYPI_TEST_USERNAME" -p "$PYPI_TEST_PASSWORD"
      deploy:
        provider: pypi
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
    
    - name: Deploy
      if: branch = master
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      script:
        - twine upload dist/* -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD"
      deploy:
        provider: pypi
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
      
    - name: Clean
      script:
        - dir
        - rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
        - dir