# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

os: linux

dist: xenial

install: pip install -r requirements.txt

script: pytest

jobs:
  include:
    - stage: Orient
      script:
        - dir
    
    - stage: Test
      script: pytest
    
    - stage: Deploy
      name: "Deploy to PyPi Test"
      script:
        - python setup.py sdist bdist_wheel
        # - twine upload dist/* -r testpypi -u ${{ secrets.PYPI_TEST_USERNAME }} -p ${{ secrets.PYPI_TEST_PASSWORD }}
      name: Deploy to PyPi
      if: branch = master
      deploy:
        provider: pypi
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        cleanup: true
        skip_existing: true
        on:
          branch: master
          # tags: true

    - stage: Clean
      name: Run Clean
      script:
        rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
      name: Verify Clean
      script:
        - pwd
        - tree