# Upon a push to master, runs tests and deploys to PyPi
language: python

python:
  "3.8"

install:
  pip install -r requirements.txt

script:
  pytest

deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDU3N2EzMTNmLTkwNTktNGE5NS1hN2M5LWUyOWI1Y2I2MDdjMgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgEE2yMWe7Ra-fBRwOyAg5xnBFR54BkGJN4y9Y-CobrVk"
  skip_cleanup: true
  skip_existing: true