# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

os: linux

dist: xenial

install: pip install -r requirements.txt

script: pytest

jobs:
  include:
    - name: Orient
      script:
        - dir
    
    - name: Test
      script: pytest
    
    - name: Build
      script:
        - python setup.py sdist bdist_wheel
    
    - name: Deploy
      if: branch = master
      deploy:
        provider: pypi
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        cleanup: true
        skip_existing: true
        on:
          branch: master
          # tags: true

    - name: Clean
      script:
        rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
    
    - name: Verify Clean
      script:
        - dir