# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

# USE LINUX OR WINDOWS PS??
#   HOW TO GET ENV VARIABLES FROM GIT -> SHELL ???
os: linux

dist: xenial

jobs:
  include:
    - name: Orient
      script:
        - dir
    
    - name: Requirements
      script:
        - pip install -r requirements.txt
    
    - name: Test
      script:
        - pytest
    
    - name: Build
      script:
        - python setup.py sdist bdist_wheel
    
    - name: Deploy to testpypi
      script:
        - $TEST_USERNAME = $PYPI_TEST_USERNAME
        - $TEST_PASSWORD = $PYPI_TEST_PASSWORD
        - twine upload dist/* -r testpypi -u ${TEST_USERNAME} -p ${TEST_PASSWORD}
    
    - name: Deploy to pypi
      if: branch = master
      script:
        - $USERNAME = $PYPI_USERNAME
        - $PASSWORD = $PYPI_PASSWORD
        - twine upload dist/* -u ${USERNAME} -p ${PASSWORD}
    
    - name: Clean
      script:
        - dir
        - rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
        - dir