# Runs tests and deploys to PyPi
# Only occurs on a tagged push to master 

language: python

python: "3.8"

install: pip install -r requirements.txt

script: pytest

stages:
  - Orient
  - Test
  - Deploy-Test
  - Deploy
    if: branch = master
  - Clean
    if: branch = master
  - Verify Clean

jobs:
  include:
    - stage: Orient
      script:
        - pwd
        - tree
    
    - stage: Test
      script: pytest
    
    - stage: Deploy-Test
      script:
        - python setup.py sdist bdist_wheel
        - twine upload -r testpypi dist/*
    
    - stage: Deploy
      script:
        - python setup.py sdist bdist_wheel -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
      deploy:
        provider: pypi
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        cleanup: true
        skip_existing: true
        on:
          branch: master
          tags: false
        
    - stage: Clean
      script:
        rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info
    
    - stage: Verify Clean
      script:
        - pwd
        - tree